### ISSUE TITLE
Refactor UI to use Table API

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TECModule#19]
Refactor all editor configuration UIs to use the Table API and follow UI guidelines.  Table API permits use of DataGrid controls or multicolumn listbox for channel configuration.  https://github.com/LabVIEW-DCAF/Table-API

UI guidelines will be posted soon.

**Comment by becega** [comment]
This modules tables wont get that much benefit from table API. There is no actions done on the tables all is with buttons.  Not sure we need to  do this.

**Comment by pollockm** [comment]
Yep.
