### ISSUE TITLE
Cannot add TEC module if cRIO target type is Linux RT x64

### ISSUE THREAD

**Issue by fmussi** [LabVIEW-DCAF/TECModule#25]
If che cRIO target type is set to Linux RT x64, I cannot select UDP \ TEC module from menu:

![image](https://cloud.githubusercontent.com/assets/8535457/20759716/01cd83a4-b71e-11e6-826e-bcd81f28c2f0.png)

Temporary workaround is to set cRIO to different target type, add the module, and set cRIO back to Linux RT 64

![image](https://cloud.githubusercontent.com/assets/8535457/20759807/5d043a1a-b71e-11e6-9ad5-66723fb25baf.png)

**Comment by Beazurt** [comment]
This is easy to fix by changing the 'Get Supported Targets' VI to use the 'list all targets' VI. 

FYI, code should still run on a target with a mismatching 'Target Type'.
